name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    # - name: Upload coverage reports to Codecov
    #   run: |
    #     curl -Os https://uploader.codecov.io/latest/linux/codecov
    #     chmod +x codecov
    #     ./codecov -t ${{secrets.CODECOV_TOKEN}} --verbose \
    #       --enterprise-url https://ff46-2001-e60-87e3-be06-ac0f-c47d-5f41-5281.ngrok-free.app upload-process

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}